# -*- coding: utf-8 -*-
"""p106.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e28MdC3Pj3r6LiV-UU6TM4JVlSrCDW8O
"""

from google.colab import files 
data_to_load= files.upload()

from google.colab import files
data_to_upload=files.upload()

from numpy.lib.function_base import corrcoef
import csv
import plotly.express as px
import numpy as np

coffee=[]
sleep=[]

with open("coffee.csv")as f:
  reader=csv.DictReader(f)
  for i in reader:
    coffee.append(float(i["Coffee in ml"]))
    sleep.append(float(i["sleep in hours"]))

correlation=np.corrcoef(coffee,sleep)
print(correlation[0,1])

marks=[]
attendence=[]

with open("Student Marks.csv") as f:
  reader=csv.DictReader(f)
  for i in reader:
    marks.append(float(i["Marks In Percentage"]))
    attendence.append(float(i["Days Present"]))
  
correlation=np.corrcoef(marks,attendence)
print(correlation[0,1])